Development sasha
threefoldfoundation/info_manual3 pull request #28
Opened 2021-12-09 16:48 UTC by sasha-astiadi

2021-12-09 20:23 UTC, xmonader requested changes
Caprover doesn't belong to tfchain portal. its doc exists here https://github.com/threefoldfoundation/info_manual3/blob/development/wiki/weblets/weblets_caprover.md if you want to improve it.

2021-12-09 20:23 UTC, xmonader commented on wiki/sidebar.md
> +  - [Virtual Machines](weblets_vm)
Move back to singular

2021-12-09 20:23 UTC, xmonader commented on wiki/getstarted/getstarted_toc.md
> +- [Install Caprover](tfchain_portal_caprover)
Caprover has nothing to do with tfchain portal, its qlso documented already in weblets directory

2021-12-09 20:23 UTC, xmonader commented on wiki/manual3_home_new.md
> +**ThreeFold Grid 3.0 Manual** is is a open-sourcedocumentation project currently maintained by ThreeFold Foundation's internal team, and constantly undergoes evolving documentation phases. Help us im
Typo: open Source documentation

2021-12-09 20:23 UTC, xmonader commented on wiki/tfchain_portal/tfchain_portal_caprover.md
> +## Your First Tutorial, lets install caprover
Remove this file from portal directory directory, check in weblets directory content.

2021-12-14 09:35 UTC, sasha-astiadi commented
@xmonader conversation resolved, changes made, please review again

2022-01-20 17:09 UTC, closed without merging