add more tfchain docs
threefoldfoundation/info_manual3 pull request #88
Opened 2022-08-16 13:22 UTC by DylanVerstraete

- Connection price
- Node certifiers

2022-10-13 16:08 UTC, renauter requested changes
Clear enough, I just found some details

Regarding the PNG files, would be good to crop the top web browser details and blur the selected account name

2022-10-13 16:08 UTC, renauter commented on wiki/tfchain/tfchain_home.md
> +Node certifiers are entities who are allowed to set a node's certification level to `Certified`. The DAO can propose to add / remove entities that can certify nodes. This is usefull for allowing appr
incomplete phrase here:
> A certified farms 25% more tokens than `Diy` nodes.

Should be replaced by

> Certified nodes farm 25% more tokens than `Diy` nodes. 

or 

> A certified node farms 25% more tokens than a `Diy` node.

2022-10-13 16:08 UTC, renauter commented on wiki/tfchain/tfchain_home.md
> +
Also it would be good to add a link to node certification wiki page if there is
I found this
https://github.com/threefoldfoundation/info_manual3/blob/1613b2495f3ef5a67cbe6cb5b3baaaec6c085c8e/wiki/tfchain/tfchain_dao.md#cerfified-farms
and this 
https://forum.threefold.io/t/gep-gold-certified-farming-specs/2925
and 50% is mentioned instead of 25%, should be sync btw...

2022-10-14 07:49 UTC, DylanVerstraete commented on wiki/tfchain/tfchain_home.md
> +
Well, certified nodes is different than gold certified farms. A certified node is a node which bios is locked by an approved reseller

2022-10-14 22:41 UTC, renauter commented on wiki/tfchain/tfchain_home.md
> +
Ok, confusing part I confess...
One can easily believe that certified nodes comes from gold certified farm, which is not the case  :)

2022-10-14 22:47 UTC, renauter approved these changes
LGTM
Just remains the suggestion for cropping PNG files

2022-11-16 08:46 UTC, merged